[app]
  #app 名称
  name = "探索者"
  slogan = "Stay Hungry Stay Foolish"
  #app url
  url  = "https://wsqyouth.cn"
  port = 8181
  #单元测试调试信息
  debug = false
  #网站备案号
  icp = "深ICP备15054073号-2"
  #github Webhooks中配置的 Secret
  secret = "goblog"
  #每页最多显示文章数
  limit = 10
#资源文件配置
[res]
    root_dir = "/home/coopers/workspace/blog_docs"
    #文章目录
    docs_dir = "/home/coopers/workspace/blog_docs/docs"
    #文档目录
    books_dir = "/home/coopers/workspace/blog_docs/books"
[image_host]
    #用户名
    username = "admin"
    #密码
    password = "admin"
    #访问路由
    path = "/imghost"
    #图片目录
    img_dir = "static/uploads/image"
